---
- hosts: web_servers
  become: true
  tasks: 

  - name: create directory on client nodes
    file:
      path: /home/ubuntu/task
      state: directory
      mode: '0755'
      
  - name: copy 10-barbican_wsgi_main.conf to client nodes
    copy: 
      src: ~/Desktop/ansible-task/nokia/10-barbican_wsgi_main.conf
      dest: /home/ubuntu/task/
      mode: '0644'

  - name: change processes value to two in 10-barbican_wsgi_main.conf
    replace: 
      path: /home/ubuntu/task/10-barbican_wsgi_main.conf
      regexp: 'processes=[0-9]{1,2}' 
      replace: 'processes=2'

- hosts: localhost
  tasks: 

  - name: (LOCAL) change processes value to two in 10-barbican_wsgi_main.conf
    replace:
      path: ~/Desktop/ansible-task/nokia/10-barbican_wsgi_main.conf
      regexp: 'processes=[0-9]{1,2}'
      replace: 'processes=2'
     

