---

- hosts: def
  become: true
  tasks:
  
  - name: update repo index
    apt: 
      update_cache: yes

  - name: remove apache2 package 
    apt:
      name: apache2
      state: present    

  - name: remove php support for apache
    apt: 
      name: libapache2-mod-php
      state: present

