---
- hosts: web_servers
  become: true
  tasks: 

  - name: change file content to original value in client nodes
    lineinfile:
      path: /home/ubuntu/task/10-barbican_wsgi_main.conf
      search_string: 'WSGIDaemonProcess'
      line: '  WSGIDaemonProcess barbican-api display-name=barbican_wsgi_main group=barbican processes=80 threads=1 user=barbican'

  - name: delete files in client nodes
    file:
      path: /home/ubuntu/task/10-barbican_wsgi_main.conf
      state: absent

- hosts: localhost
  become: true
  gather_facts: false
  tasks:

  - name: change file content to original value (LOCAL)
    lineinfile:
      path: /home/ilya/Desktop/ansible-task/nokia/10-barbican_wsgi_main.conf
      search_string: 'WSGIDaemonProcess'
      line: '  WSGIDaemonProcess barbican-api display-name=barbican_wsgi_main group=barbican processes=80 threads=1 user=barbican'
   

