---
- hosts: web_servers
  become: true
  tasks: 

  - name: change file content to original value in client nodes
    replace:
      path: /home/ubuntu/task/10-barbican_wsgi_main.conf
      regexp: 'processes=[0-9]{1,2}'
      replace:  'processes=80'

  - name: delete files in client nodes
    file:
      path: /home/ubuntu/task/10-barbican_wsgi_main.conf
      state: absent

- hosts: localhost
  become: true
  gather_facts: false
  tasks:

  - name: change file content to original value (LOCAL)
    replace:
      path: /home/ilya/Desktop/ansible-task/nokia/10-barbican_wsgi_main.conf
      regexp: 'processes=[0-9]{1,2}'
      replace: 'processes=80'
   

