---

- hosts: all
  become: true
  tasks:
 
  - name: install updates (Amazon)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Amazon"

  - name: install updates (Ubuntu)
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_serv
  become: true
  tasks:

  - name: apache and php 
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: apache and php for Amazon 
    yum: 
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Amazon" 
